Hit the api
Ochiengsteven/leader-board pull request #2
Opened 2023-07-25 16:47 UTC by Ochiengsteven

This pull request addresses the project requirements by integrating the Leaderboard API, creating a new game, and implementing the "Refresh" and "Submit" buttons for scores. Additionally, the codebase now utilizes arrow functions, async, and await to consume the API efficiently.

### Changes Made

- Integrated the Leaderboard API by reading its documentation to understand its functionalities and endpoints.

- Created a new game using the API, and saved the game ID returned by the API for future reference.

- Implemented the "Refresh" button, which fetches all the scores for the game created by the user from the API. The retrieved data is parsed as JSON and displayed to the user.

- Implemented the "Submit" button that allows users to save their scores for the game created by them. The relevant score data is sent to the API for storage and leaderboard update.

- Refactored existing code and replaced traditional functions with arrow functions to improve code readability and maintain consistency.

- Utilized async and await JavaScript features to consume the API asynchronously, enhancing overall performance and responsiveness.

2023-07-25 17:02 UTC, fobadara requested changes
Hi @Ochiengsteven, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## Highlights
✅ Clean code
✅ Use of async and await

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-25 17:02 UTC, fobadara commented on src/index.js
> +  function createScoreFromInputs() {
[REQUIRED] Kindly change this to an arrow function. This is a requirement for this milestone.

2023-07-25 17:02 UTC, fobadara commented on src/index.js
> +  function handleKeyPress(e) {
[REQUIRED] Kindly change this to an arrow function. This is a requirement for this milestone.

2023-07-25 17:02 UTC, fobadara commented on src/index.js
> +  function handleSubmit(e) {
[REQUIRED] Kindly change this to an arrow function. This is a requirement for this milestone.

2023-07-26 08:24 UTC, andersonlebon approved these changes
## Hi  @Ochiengsteven 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![nodding-yes](https://user-images.githubusercontent.com/65068771/143095390-344d1cb0-b853-4b91-8662-5d9049dc9e60.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 


## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question `@andersonlebon` so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-07-26 08:24 UTC, andersonlebon commented on src/index.js
> +    // eslint-disable-next-line no-unused-vars
## [OPTIONAL]

- [ ]  Kindly make sure any linter checker is not disabled, they are really important as the help you structure your code and prevent future bugs by following  best practices, kindly solve them instead

2023-07-26 08:24 UTC, andersonlebon commented on src/index.js
> +  // eslint-disable-next-line no-unused-vars
## [OPTIONAL]

- [ ]  Kindly make sure any linter checker is not disabled, they are really important as the help you structure your code and prevent future bugs by following  best practices, kindly solve them instead

2023-07-27 14:25 UTC, merged